In [1]:
from __future__ import print_function
import numpy as np

In [2]:
# basic operations with list/array
data1 = [1, 2, 3, 4, 5]

In [7]:
arr1 = np.array(data1)
data2 = [range(1, 5), range(5, 9)]

In [8]:
arr1.dtype

dtype('int64')

In [10]:
print(arr1.size)
print(len(data2))

5
2


In [13]:
# reshaping
arr = np.arange(10, dtype=float).reshape((2, 5))
print(arr)
print(arr.shape)
print(arr.reshape(5, 2))

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
(2, 5)
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


In [20]:
# add an axis
a = np.array([0, 1])
a_col = a[:, np.newaxis]
print(a_col)

[[0]
 [1]]


In [22]:
# exercise 
# for each column find the row index of the minimum value
# write a function standardize(X) that returns an array whose columns are
# centered and scaled by (std-dev)
X = np.random.randn(4, 2)
print(X)

[[ 0.7085471  -0.68568825]
 [-1.90435726  2.42781977]
 [-0.85262891  1.52620428]
 [-0.26066943  0.48142563]]


In [23]:
minValues = []
for i in np.array(X):
    minValues.append(np.min(i))
print(minValues)

[-0.6856882467985358, -1.9043572635996373, -0.8526289099090703, -0.26066943442636936]


In [24]:
def standardize(X):
    for i in np.array(X):
        print(np.std(i))

In [25]:
standardize(X)

0.6971176758933701
2.1660885150693048
1.18941659346511
0.371047533693891
